version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nery
      POSTGRES_PASSWORD: 161204
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://nery:161204@db:5432/mi_base_de_datos?sslmode=disable"
    restart: unless-stopped

volumes:
  postgres_data: