services:
  db:
    image: postgres:16
    container_name: postgres_laverdaderabase
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: nery
      POSTGRES_PASSWORD: 161204
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nery -d mi_base_de_datos"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://nery:161204@db:5432/mi_base_de_datos?sslmode=prefer"
    restart: unless-stopped

volumes:
  postgres_data: