CREATE TABLE matches (
    id SERIAL PRIMARY KEY,
    team1 VARCHAR(50) NOT NULL,
    team2 VARCHAR(50) NOT NULL,
    score1 INT DEFAULT 0,
    score2 INT DEFAULT 0,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
